import type { PrismaClient } from "@prisma/client";
import type { ComplianceSeedRecord } from "./seed-compliance";

/**
 * The 32 corporate/non-job opportunity source compliance records researched and recorded in
 * docs/source-compliance.md under "Corporate Opportunity Sources (Batch 2 — 2026-09-03)".
 *
 * Same methodology and fail-closed rule as the Batch 1 records in seed-compliance.ts: live
 * robots.txt/ToS fetches, not memory; NOT_ALLOWED is never implemented, UNCLEAR_REQUIRES_REVIEW
 * never auto-runs.
 *
 * `lastPolicyCheckAt` matches the date the live research in docs/source-compliance.md was
 * actually performed — do not bump this without re-doing the research.
 */
const POLICY_CHECK_DATE = new Date("2026-09-03T00:00:00.000Z");

export const CORPORATE_COMPLIANCE_SEED_RECORDS: ComplianceSeedRecord[] = [
  // ---- ALLOWED ----
  {
    sourceName: "Hugging Face",
    sourceUrl: "https://huggingface.co",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "allowed",
    tosReviewed: true,
    tosUrl: "https://huggingface.co/terms-of-service",
    tosSummary:
      "No clause addressing automated access, scraping, crawling, bots, or data mining was found.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: true,
    rssUrl: "https://huggingface.co/blog/feed.xml",
    sitemapAvailable: true,
    sitemapUrl: "https://huggingface.co/sitemap.xml",
    automatedAccessStatus: "ALLOWED",
    permittedAdapterType: "rss",
    complianceNotes:
      "Cleanest result of the 32 — open robots.txt, a working RSS feed, and a directly-reviewed ToS with no scraping prohibition. Discovery (RSS) and the authoritative record (the linked hackathon page) are both first-party huggingface.co content.",
    reviewRequired: false,
  },

  // ---- ALLOWED_WITH_RESTRICTIONS ----
  {
    sourceName: "Google",
    sourceUrl: "https://google.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "allowed",
    tosReviewed: false,
    tosUrl: "https://policies.google.com/terms",
    tosSummary:
      "General Google terms condition automated access on robots.txt compliance and restrict using content to train ML models; whether this is the controlling document for the GSoC/DeepMind subdomains specifically was not confirmed.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: true,
    rssUrl: "https://blog.google/rss/",
    sitemapAvailable: true,
    sitemapUrl: "https://developers.google.com/sitemap.xml",
    automatedAccessStatus: "ALLOWED_WITH_RESTRICTIONS",
    permittedAdapterType: "sitemap_static_html",
    complianceNotes:
      "robots.txt is permissive on the program/news paths actually needed; the restriction is the unconfirmed applicability of the general Google ToS to program-specific subdomains (e.g. summerofcode.withgoogle.com), not any found prohibition.",
    reviewRequired: false,
  },
  {
    sourceName: "Google DeepMind",
    sourceUrl: "https://deepmind.google",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "allowed",
    tosReviewed: false,
    tosSummary:
      "No DeepMind-specific terms page was found (a guessed terms URL 404'd); likely falls under Google's general terms but not confirmed via a service-specific terms list.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: true,
    automatedAccessStatus: "ALLOWED_WITH_RESTRICTIONS",
    permittedAdapterType: "sitemap_static_html",
    complianceNotes:
      "robots.txt and sitemap both support compliant static discovery; the ToS applicability gap and absence of RSS/API keep it at restrictions rather than fully clear.",
    reviewRequired: false,
  },
  {
    sourceName: "GitHub",
    sourceUrl: "https://github.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "partial",
    tosReviewed: false,
    tosSummary:
      "Section D.9 (Access Reciprocity) conditions automated collection of public content on reciprocity specifically for training commercially available AI models; Section H (API terms) warns against abusive/excessive request volume — not a blanket scraping ban, but a real condition given Polaris's AI-classification use.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: true,
    rssUrl: "https://github.blog/feed/",
    sitemapAvailable: false,
    automatedAccessStatus: "ALLOWED_WITH_RESTRICTIONS",
    rateLimit: "No numeric limit found for HTML scraping; API terms mention suspension for abusive/excessive requests.",
    permittedAdapterType: "sitemap_static_html",
    complianceNotes:
      "robots.txt is clean on the Education page; the ToS Access Reciprocity clause (Section D.9) is a real nuance given Polaris's downstream AI-classification use — confirm it doesn't trip the 'training commercially available AI models' condition before implementing.",
    reviewRequired: false,
  },
  {
    sourceName: "Microsoft",
    sourceUrl: "https://microsoft.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "partial",
    tosReviewed: false,
    tosUrl: "https://microsoft.com/en-us/legal/terms-of-use",
    tosSummary:
      "Bars 'web scraping, web harvesting, or web data extraction' but that clause is explicitly scoped to AI services; ambiguous whether it governs the public Learn/Research docs pages Polaris would use.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: true,
    rssUrl: "https://news.microsoft.com/feed/",
    sitemapAvailable: false,
    automatedAccessStatus: "ALLOWED_WITH_RESTRICTIONS",
    permittedAdapterType: "manual",
    complianceNotes:
      "The ToS scraping clause is scoped to AI services with ambiguous applicability to Learn/Research docs. The PhD Fellowship is also currently paused (redirected to the AI & Society Fellows program), so it isn't ingestible as an open opportunity regardless of compliance.",
    reviewRequired: false,
  },
  {
    sourceName: "AWS (Amazon Web Services)",
    sourceUrl: "https://aws.amazon.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "partial",
    tosReviewed: false,
    tosSummary:
      "AWS Service Terms had no scraping clause found; Amazon.com's general Conditions of Use returned HTTP 503 on repeated attempts, leaving the review inconclusive.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: true,
    rssUrl: "https://aws.amazon.com/blogs/aws/feed/",
    sitemapAvailable: false,
    automatedAccessStatus: "ALLOWED_WITH_RESTRICTIONS",
    permittedAdapterType: "sitemap_static_html",
    complianceNotes:
      "robots.txt disallows /blogs/ (including the blog RSS feed path itself) and /activate/hackathons|accelerators|events — the two most obvious ingestion paths are both robots.txt-disallowed; only AWS Educate and non-disallowed AWS Activate marketing pages are clearly fair game. Do not use the /blogs/ RSS feed despite it resolving.",
    reviewRequired: false,
  },
  {
    sourceName: "IBM",
    sourceUrl: "https://ibm.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "allowed",
    tosReviewed: true,
    tosUrl: "https://ibm.com/legal/terms",
    tosSummary:
      "Unusually explicit and favorable: crawlers are permitted exactly as allowed by robots.txt, and all other spidering/data-mining is prohibited. Since robots.txt doesn't block the relevant paths, robots.txt-compliant crawling is affirmatively permitted.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: false,
    automatedAccessStatus: "ALLOWED_WITH_RESTRICTIONS",
    permittedAdapterType: "sitemap_static_html",
    complianceNotes:
      "One of the strongest ToS results in the batch — IBM's terms affirmatively greenlight robots.txt-compliant crawling. Capped at restrictions only because no feed/API exists and skillsbuild.org's own robots.txt wasn't independently confirmed; IBM Research's careers page redirects into a generic job-search portal and was excluded per the no-job-boards rule.",
    reviewRequired: false,
  },
  {
    sourceName: "Salesforce",
    sourceUrl: "https://salesforce.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "allowed",
    tosReviewed: false,
    tosUrl: "https://salesforce.com/company/legal/agreements/",
    tosSummary:
      "Only the legal-agreements hub page was reached, which links out to the actual Terms of Service without containing the text itself — not conclusively reviewed.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: true,
    rssUrl: "https://salesforce.com/blog/feed/",
    sitemapAvailable: false,
    automatedAccessStatus: "ALLOWED_WITH_RESTRICTIONS",
    permittedAdapterType: "sitemap_static_html",
    complianceNotes:
      "Trailhead is real, active, and clearly distinct from a job board; capped at restrictions because the actual site ToS text couldn't be read.",
    reviewRequired: false,
  },
  {
    sourceName: "SAP",
    sourceUrl: "https://www.sap.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "partial",
    tosReviewed: false,
    tosSummary:
      "Every direct fetch of www.sap.com pages (homepage, terms-of-use, academic-alliances) returned HTTP 403, consistent with an anti-bot/WAF challenge on the apex domain; pages.community.sap.com and news.sap.com fetched normally.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: true,
    rssUrl: "https://news.sap.com/feed/",
    sitemapAvailable: false,
    automatedAccessStatus: "ALLOWED_WITH_RESTRICTIONS",
    permittedAdapterType: "sitemap_static_html",
    complianceNotes:
      "The apex sap.com domain is WAF-blocked, so implementation must target the pages.community.sap.com subdomain (hosting University Alliances) specifically, not the corporate domain.",
    reviewRequired: false,
  },
  {
    sourceName: "Qualcomm",
    sourceUrl: "https://qualcomm.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "allowed",
    tosReviewed: false,
    tosUrl: "https://qualcomm.com/site/terms-of-use",
    tosSummary:
      "The terms-of-use page appears client-side-rendered; every fetch returned only the page's <title>, not the terms body — a technical/rendering gap, not a found prohibition or anti-bot block.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: true,
    sitemapUrl: "https://www.qualcomm.com/sitemap.xml",
    automatedAccessStatus: "ALLOWED_WITH_RESTRICTIONS",
    permittedAdapterType: "sitemap_static_html",
    complianceNotes:
      "Both a real fellowship page and a currently-open innovation challenge were verified live; capped at restrictions because the ToS text couldn't be retrieved (JS rendering gap) and no feed/API exists.",
    reviewRequired: false,
  },
  {
    sourceName: "Deloitte",
    sourceUrl: "https://deloitte.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "allowed",
    tosReviewed: false,
    tosUrl: "https://deloitte.com/global/en/legal/legal.html",
    tosSummary:
      "No explicit scraping/bot clause found, but this page may not be Deloitte's complete Acceptable Use Policy — not conclusively reviewed.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: true,
    sitemapUrl: "https://www.deloitte.com/sitemap_index.xml",
    automatedAccessStatus: "ALLOWED_WITH_RESTRICTIONS",
    permittedAdapterType: "sitemap_static_html",
    complianceNotes:
      "The Consulting Undergraduate Case Competition page is genuinely distinct from job listings and robots.txt is permissive; capped at restrictions pending full ToS/AUP confirmation and absent any feed.",
    reviewRequired: false,
  },
  {
    sourceName: "Accenture",
    sourceUrl: "https://accenture.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "partial",
    tosReviewed: false,
    tosUrl: "https://accenture.com/us-en/support/terms-of-use",
    tosSummary:
      "No scraping clause found, but references a separate Acceptable Use Policy at a URL that 404'd — not conclusively reviewed.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: true,
    sitemapAvailable: true,
    sitemapUrl: "https://www.accenture.com/sitemap-index.xml",
    automatedAccessStatus: "ALLOWED_WITH_RESTRICTIONS",
    permittedAdapterType: "sitemap_static_html",
    complianceNotes:
      "Distinct, verified program pages (Innovation Challenge MBA, Externship, Student Leadership Program) plus permissive robots.txt, offset by an unreviewed AUP and a newsroom feed that requires registration and isn't usable as a no-friction feed.",
    reviewRequired: false,
  },
  {
    sourceName: "EY",
    sourceUrl: "https://ey.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "allowed",
    tosReviewed: false,
    tosUrl: "https://ey.com/en_gl/legal-and-privacy/legal-statement",
    tosSummary:
      "No scraping clause found, but no page unambiguously titled 'Terms of Use' was located for the main site — not conclusively reviewed.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: true,
    automatedAccessStatus: "ALLOWED_WITH_RESTRICTIONS",
    permittedAdapterType: "sitemap_static_html",
    complianceNotes:
      "Unusually explicit, permissive robots.txt that names anthropic-ai as an allowed agent, plus a verified distinct program page (EY-Parthenon NextGen Women); capped at restrictions pending full ToS confirmation and absent any feed.",
    reviewRequired: false,
  },
  {
    sourceName: "BCG",
    sourceUrl: "https://bcg.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "partial",
    tosReviewed: true,
    tosUrl: "https://bcg.com/about/terms-of-use",
    tosSummary:
      "Covers copyright/liability/registration but has no explicit clause on scraping, robots, or data mining.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: true,
    automatedAccessStatus: "ALLOWED_WITH_RESTRICTIONS",
    permittedAdapterType: "sitemap_static_html",
    complianceNotes:
      "No anti-bot block was hit on any bcg.com-family domain (RISE by BCG, careers.bcg.com case competitions), and the reviewed ToS is silent on automation, but no RSS/API exists.",
    reviewRequired: false,
  },
  {
    sourceName: "JPMorgan / JPMorganChase",
    sourceUrl: "https://jpmorganchase.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "partial",
    tosReviewed: true,
    tosUrl: "https://jpmorganchase.com/legal/terms-and-conditions",
    tosSummary:
      "Covers copyright/use restrictions but has no explicit clause on automated access, scraping, or bots.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: true,
    automatedAccessStatus: "ALLOWED_WITH_RESTRICTIONS",
    permittedAdapterType: "sitemap_static_html",
    complianceNotes:
      "The most cleanly accessible financial-services firm researched — no anti-bot block, permissive robots.txt, ToS silent on scraping, and a confirmed sitemap index. Restricted only because no RSS/API exists and the programs-directory extraction must exclude the explicitly disallowed tech-data-product path.",
    reviewRequired: false,
  },

  // ---- UNCLEAR_REQUIRES_REVIEW ----
  {
    sourceName: "Cisco",
    sourceUrl: "https://cisco.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "partial",
    tosReviewed: true,
    tosUrl: "https://cisco.com/c/en/us/about/legal/terms-conditions.html",
    tosSummary:
      "The 'Your Use of Our Site' section explicitly prohibits 'monitoring, crawling... using bots or scripts,' directly conflicting with the AI-crawler-friendly robots.txt on the parent domain.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: true,
    automatedAccessStatus: "UNCLEAR_REQUIRES_REVIEW",
    rateLimit: "Unconfirmed crawl-delay value on netacad.com.",
    permittedAdapterType: "none",
    complianceNotes:
      "An unresolved conflict between a robots.txt that explicitly names and permits ClaudeBot on parts of cisco.com and a corporate ToS that broadly forbids bots/crawling, plus it's unconfirmed whether netacad.com is even governed by the same terms page. Needs a human legal read, not an automated guess.",
    reviewRequired: true,
  },
  {
    sourceName: "Oracle",
    sourceUrl: "https://oracle.com",
    robotsTxtStatus: "inaccessible (403)",
    robotsTxtCrawlPermission: "unknown",
    tosReviewed: false,
    tosSummary:
      "Could not retrieve any Oracle legal page; blogs.oracle.com and both candidate ToS URLs also returned 403, and education.oracle.com timed out twice.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: false,
    automatedAccessStatus: "UNCLEAR_REQUIRES_REVIEW",
    permittedAdapterType: "none",
    complianceNotes:
      "A consistent, multi-path 403 block across Oracle's main corporate domain; no workaround was attempted. Not enough was accessible to make any stronger claim than unclear.",
    reviewRequired: true,
  },
  {
    sourceName: "OpenAI",
    sourceUrl: "https://openai.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "partial",
    tosReviewed: false,
    tosSummary:
      "Both OpenAI ToS URLs returned HTTP 403 on direct fetch (anti-bot block, no workaround attempted). Credible secondary sources report a prohibition on automated scraping/data extraction except via the API, but this was not independently confirmed from OpenAI's own page text.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: true,
    automatedAccessStatus: "UNCLEAR_REQUIRES_REVIEW",
    permittedAdapterType: "none",
    complianceNotes:
      "Genuinely ambiguous — open robots.txt and a live sitemap on one hand, a credibly-reported-but-unverified scraping prohibition and a partial /events disallow on the Academy subdomain on the other. Needs a human to read the ToS past the anti-bot block before any firmer classification.",
    reviewRequired: true,
  },
  {
    sourceName: "KPMG",
    sourceUrl: "https://kpmg.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "allowed",
    tosReviewed: false,
    tosUrl: "https://kpmg.com/xx/en/misc/legal.html",
    tosSummary:
      "The main-domain ToS explicitly bars any scraper/robot/bot/spider/data-mining tool without KPMG's prior written consent, plus an AI/ML training ban — but the actual program pages live on kpmguscareers.com, a differently-hosted domain with no separately located Terms of Use.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: false,
    automatedAccessStatus: "UNCLEAR_REQUIRES_REVIEW",
    permittedAdapterType: "none",
    complianceNotes:
      "A real structural ambiguity: does the parent kpmg.com scraping ban extend to the differently-hosted kpmguscareers.com subdomain, which has its own permissive robots.txt and no located terms of its own? A legal question for a human, not further automated fetching.",
    reviewRequired: true,
  },
  {
    sourceName: "Visa",
    sourceUrl: "https://visa.com",
    robotsTxtStatus: "inconclusive (empty response)",
    robotsTxtCrawlPermission: "unknown",
    tosReviewed: true,
    tosUrl: "https://visa.com/en-us/legal",
    tosSummary:
      "No explicit scraping/bot/data-mining clause found; only a general 'must not damage or impair the site' restriction.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: false,
    automatedAccessStatus: "UNCLEAR_REQUIRES_REVIEW",
    permittedAdapterType: "none",
    complianceNotes:
      "Visa's content pages (Black Scholars and Jobs Program, Visa Foundation) fetched successfully with real program content — not a hard block — but without a readable robots.txt a crawl-directive-based verdict can't honestly be ALLOWED yet. Retry the robots.txt fetch to confirm the empty response is transient.",
    reviewRequired: true,
  },

  // ---- NOT_ALLOWED ----
  {
    sourceName: "Meta",
    sourceUrl: "https://meta.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "disallowed",
    tosReviewed: true,
    tosUrl: "https://facebook.com/legal/terms",
    tosSummary:
      "Clause 3.2(3) states users cannot access or compile data from Meta's products using automated tools without prior permission (fetched in a non-English locale; substance consistent across fetches but should be re-verified in English before citing verbatim in a legal context).",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: false,
    automatedAccessStatus: "NOT_ALLOWED",
    rateLimit: "N/A",
    permittedAdapterType: "none",
    complianceNotes:
      "about.meta.com/robots.txt explicitly disallows a named list of bots including ClaudeBot (alongside GPTBot, Google-Extended, PerplexityBot); ai.meta.com blocks several scraper bots outright. Combined with the ToS clause requiring prior permission for automated data collection, this is clear and unambiguous even though the Meta Research program page itself is real.",
    reviewRequired: false,
  },
  {
    sourceName: "Adobe",
    sourceUrl: "https://adobe.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "partial",
    tosReviewed: true,
    tosUrl: "https://adobe.com/legal/terms.html",
    tosSummary:
      "Section 6.18 explicitly prohibits data mining/scraping for machine learning; Section 6.6 prohibits accessing the service by any means other than the provided interface; Section 17 restricts using outputs to train AI systems.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: false,
    automatedAccessStatus: "NOT_ALLOWED",
    rateLimit: "N/A",
    permittedAdapterType: "none",
    complianceNotes:
      "The most explicit and unambiguous ToS prohibition in the batch — it names 'data scraping for machine learning' directly, precisely what Polaris's ingestion+AI-classification pipeline does. The ToS is dispositive even though the education page itself resolves and parts of robots.txt are permissive.",
    reviewRequired: false,
  },
  {
    sourceName: "NVIDIA",
    sourceUrl: "https://nvidia.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "allowed",
    tosReviewed: true,
    tosUrl: "https://nvidia.com/en-us/about-nvidia/legal-info/",
    tosSummary:
      "Explicit and unambiguous prohibition of any robot, spider, scraper, crawler, or data mining/gathering/extraction tool used to access, acquire, copy, or monitor any portion of the Site — directly covering the verified DLI training pages.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: true,
    rssUrl: "https://blogs.nvidia.com/feed/",
    sitemapAvailable: false,
    automatedAccessStatus: "NOT_ALLOWED",
    rateLimit: "Ban on causing 'unreasonable or disproportionately large load' (main site ToS).",
    permittedAdapterType: "none",
    complianceNotes:
      "robots.txt is permissive but the directly-reviewed ToS is an explicit, unambiguous prohibition on exactly this activity for the main site — ToS controls. The separate blogs.nvidia.com subdomain's RSS may flag an announcement (discovery-only) but the actual program record must not be built from the blog alone, and the main DLI pages it would point to are ToS-prohibited anyway.",
    reviewRequired: false,
  },
  {
    sourceName: "Intel",
    sourceUrl: "https://intel.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "allowed",
    tosReviewed: true,
    tosUrl: "https://intel.com/content/www/us/en/legal/terms-of-use.html",
    tosSummary:
      "Section 4.1.14 bars automated searches/bots/link checkers/scraping technologies without Intel's prior written permission; 4.1.16 bars text/data mining or harvesting metadata; 4.1.17 bars systematic/bulk downloading.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: true,
    automatedAccessStatus: "NOT_ALLOWED",
    rateLimit: "N/A",
    permittedAdapterType: "none",
    complianceNotes:
      "robots.txt alone would look fine, but a directly-verified, explicit contractual prohibition (Sections 4.1.14/4.1.16/4.1.17) overrides that. Only manual/periodic human review of the Innovator Program page is appropriate absent written permission from Intel.",
    reviewRequired: false,
  },
  {
    sourceName: "Anthropic",
    sourceUrl: "https://anthropic.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "allowed",
    tosReviewed: true,
    tosUrl: "https://anthropic.com/legal/consumer-terms",
    tosSummary:
      "Explicitly bars users from crawling, scraping, or otherwise harvesting data from the Services other than as permitted, and separately bars accessing the Services through automated or non-human means except via an Anthropic API Key or explicit permission.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: true,
    automatedAccessStatus: "NOT_ALLOWED",
    rateLimit: "N/A",
    permittedAdapterType: "none",
    complianceNotes:
      "A directly-fetched, unambiguous, primary-source ToS prohibition on non-API automated access despite an open robots.txt — that contractual restriction controls. Both the Fellows Program and AI for Science Program pages are real and current; manual/periodic human review is the only compliant path absent an API key or explicit written permission.",
    reviewRequired: false,
  },
  {
    sourceName: "PwC",
    sourceUrl: "https://pwc.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "allowed",
    tosReviewed: true,
    tosUrl: "https://pwc.com/gx/en/legal-notices/terms-and-conditions.html",
    tosSummary:
      "Explicitly prohibits using any robot/spider/search-retrieval application or other automatic device to retrieve, index, scrape, data mine, or otherwise gather content without PwC's express prior written consent, plus a ban on systematic downloading/storage and using content for AI training.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: true,
    rssUrl: "https://pwc.com/gx/en/site-map/rss-feeds.html",
    sitemapAvailable: true,
    sitemapUrl: "https://www.pwc.com/sitemap.xml",
    automatedAccessStatus: "NOT_ALLOWED",
    rateLimit: "N/A",
    permittedAdapterType: "none",
    complianceNotes:
      "robots.txt technically permits crawling (fetched via curl 200; WebFetch itself got 403, an edge bot-management inconsistency), but the directly-reviewed ToS is an explicit, unambiguous prohibition that overrides the technical permissiveness. The one official RSS feed only covers global press releases, not program data.",
    reviewRequired: false,
  },
  {
    sourceName: "McKinsey",
    sourceUrl: "https://mckinsey.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "disallowed",
    tosReviewed: true,
    tosUrl: "https://mckinsey.com/terms-of-use",
    tosSummary:
      "Dated Jan 28, 2025 — explicitly prohibits accessing, searching, or collecting/mining/extracting data (including by crawling or scraping) from the Site by any means without McKinsey's express written permission, plus a ban on using content to train/fine-tune/ground AI systems.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: true,
    sitemapAvailable: true,
    automatedAccessStatus: "NOT_ALLOWED",
    rateLimit: "N/A",
    permittedAdapterType: "none",
    complianceNotes:
      "Both an explicit ToS prohibition and an explicit robots.txt disallow on the one relevant program path (mckinsey.org/forward/), plus network-level friction consistent with active bot-blocking infrastructure — only a real browser render surfaced the robots.txt content at all; no workaround was attempted.",
    reviewRequired: false,
  },
  {
    sourceName: "Bain",
    sourceUrl: "https://bain.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "allowed",
    tosReviewed: true,
    tosUrl: "https://bain.com/about/terms/",
    tosSummary:
      "Explicitly prohibits use of any robot, spider, scraper, or other automated means to access the Site, and any data mining, data gathering, or extraction method.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: true,
    automatedAccessStatus: "NOT_ALLOWED",
    rateLimit: "N/A",
    permittedAdapterType: "none",
    complianceNotes:
      "robots.txt alone would look permissive, but the Terms of Use directly and explicitly bar the exact activity Polaris would perform — this overrides the robots.txt signal, exactly the pattern the compliance gate exists to catch.",
    reviewRequired: false,
  },
  {
    sourceName: "Goldman Sachs",
    sourceUrl: "https://goldmansachs.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "partial",
    tosReviewed: false,
    tosSummary:
      "Direct fetch of both the terms-and-conditions page and the disclaimer page returned HTTP 403 — not conclusively reviewed.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: true,
    sitemapAvailable: true,
    automatedAccessStatus: "NOT_ALLOWED",
    rateLimit: "N/A (moot given the access block)",
    permittedAdapterType: "none",
    complianceNotes:
      "robots.txt itself is fetchable and largely permissive, but every actual content page tested — careers/programs, terms, disclaimer, even the declared sitemap — hit a WAF 403. A clear anti-bot block on the content needed for ingestion; no workaround was attempted.",
    reviewRequired: false,
  },
  {
    sourceName: "Morgan Stanley",
    sourceUrl: "https://morganstanley.com",
    robotsTxtStatus: "inaccessible (connection reset)",
    robotsTxtCrawlPermission: "unknown",
    tosReviewed: false,
    tosSummary:
      "Blocked before any page could be read — repeated ECONNRESET on robots.txt, terms, a press release, and the diversity/inclusion page, consistent with a network-level anti-bot block.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: false,
    automatedAccessStatus: "NOT_ALLOWED",
    rateLimit: "Unknown.",
    permittedAdapterType: "none",
    complianceNotes:
      "No workaround was attempted for the connection-level block. Per the rule that third-party sources can be used for discovery but not as the record of truth, these scholarship programs (HBCU Scholars, Fisher Scholarship, Future Generation Scholarship) are not candidates for ingestion — no verifiable official URL exists to serve as the source of record.",
    reviewRequired: false,
  },
  {
    sourceName: "Bloomberg",
    sourceUrl: "https://bloomberg.com",
    robotsTxtStatus: "found",
    robotsTxtCrawlPermission: "partial",
    tosReviewed: false,
    tosSummary: "Not reviewed — deprioritized after the content-page block below.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: true,
    sitemapAvailable: true,
    automatedAccessStatus: "NOT_ALLOWED",
    permittedAdapterType: "none",
    complianceNotes:
      "The actual bloomberg.com/company/press/... page needed to verify either program (a Knowledge House hackathon partnership, a Journalism Diversity Program) returned a 403. Bloomberg's genuinely useful asset (news RSS) covers only general news/markets, not opportunity data, so there's no compliant path to the actual program record even setting the block aside.",
    reviewRequired: false,
  },
  {
    sourceName: "Mastercard",
    sourceUrl: "https://mastercard.com",
    robotsTxtStatus: "inaccessible (403)",
    robotsTxtCrawlPermission: "blocked (403)",
    tosReviewed: false,
    tosSummary: "Two separate Terms-of-Use URLs also returned 403 — not conclusively reviewed.",
    apiAvailable: false,
    apiPreferred: false,
    rssAvailable: false,
    sitemapAvailable: false,
    automatedAccessStatus: "NOT_ALLOWED",
    rateLimit: "Unknown.",
    permittedAdapterType: "none",
    complianceNotes:
      "Every mastercard.com path tested returned 403, a consistent WAF block; no workaround was attempted. Note: Mastercard Foundation (mastercardfdn.org), which runs the well-known Scholars Program, is a legally distinct Canadian charitable foundation, not attributable to Mastercard Inc. — flagged so it isn't mistakenly conflated with this corporate record.",
    reviewRequired: false,
  },
];

export async function seedCorporateComplianceRecords(prisma: PrismaClient) {
  let created = 0;
  for (const record of CORPORATE_COMPLIANCE_SEED_RECORDS) {
    const existing = await prisma.sourceComplianceRecord.findFirst({
      where: { sourceUrl: record.sourceUrl },
    });
    if (existing) continue;

    await prisma.sourceComplianceRecord.create({
      data: {
        sourceName: record.sourceName,
        sourceUrl: record.sourceUrl,
        robotsTxtStatus: record.robotsTxtStatus,
        robotsTxtCrawlPermission: record.robotsTxtCrawlPermission,
        robotsTxtCheckedAt: POLICY_CHECK_DATE,
        tosReviewed: record.tosReviewed,
        tosUrl: record.tosUrl,
        tosSummary: record.tosSummary,
        apiAvailable: record.apiAvailable,
        apiPreferred: record.apiPreferred,
        apiDocsUrl: record.apiDocsUrl,
        rssAvailable: record.rssAvailable,
        rssUrl: record.rssUrl,
        sitemapAvailable: record.sitemapAvailable,
        sitemapUrl: record.sitemapUrl,
        automatedAccessStatus: record.automatedAccessStatus,
        rateLimit: record.rateLimit,
        permittedAdapterType: record.permittedAdapterType,
        complianceNotes: record.complianceNotes,
        lastPolicyCheckAt: POLICY_CHECK_DATE,
        reviewRequired: record.reviewRequired,
      },
    });
    created++;
  }
  console.log(
    `Seeded ${created} new corporate compliance records (${CORPORATE_COMPLIANCE_SEED_RECORDS.length - created} already existed).`,
  );
}
