import { writeFileSync } from "node:fs";
import path from "node:path";
import { runFullEvaluation, type PersonaEvaluation } from "../tests/evaluation/evaluate";
import { CATALOG } from "../tests/evaluation/catalog";
import { PERSONAS } from "../tests/evaluation/personas";

function pct(n: number): string {
  return `${(n * 100).toFixed(1)}%`;
}
function num(n: number | null, digits = 2): string {
  return n == null ? "N/A" : n.toFixed(digits);
}

function personaSection(e: PersonaEvaluation): string {
  const lines: string[] = [];
  lines.push(`### Persona ${e.persona.id} — ${e.persona.name}`);
  lines.push("");
  lines.push(e.persona.description);
  lines.push("");
  lines.push(
    `**${e.eligibleCount} of ${e.totalCatalogSize}** catalog opportunities are eligible for this persona ` +
      `(${e.ineligibleCount} excluded by the hard gate).`
  );
  lines.push("");
  lines.push("**Top 10 recommendations, as actually ranked by the current engine:**");
  lines.push("");
  lines.push("| # | Score | Opportunity | Our relevance grade | Shown reasons |");
  lines.push("|---|---|---|---|---|");
  e.topResults.forEach((r, i) => {
    lines.push(
      `| ${i + 1} | ${r.score} | ${r.title} | ${r.groundTruth.relevance}/3 | ${r.reasons.join("; ") || "(none)"} |`
    );
  });
  lines.push("");

  if (e.wronglyExcludedRelevant.length > 0) {
    lines.push("**Clearly relevant opportunities that were wrongly excluded (never even reached the eligible list):**");
    lines.push("");
    for (const w of e.wronglyExcludedRelevant) {
      lines.push(`- **${w.title}** (relevance ${w.relevance}/3) — ${w.note}`);
    }
    lines.push("");
  } else {
    lines.push("No relevant opportunities were wrongly excluded for this persona.");
    lines.push("");
  }

  if (e.slippedIneligible.length > 0) {
    lines.push("**Opportunities that should have been ineligible but slipped through:**");
    lines.push("");
    for (const s of e.slippedIneligible) {
      lines.push(`- **${s.title}** — ${s.note}`);
    }
    lines.push("");
  } else {
    lines.push("No ineligible opportunities slipped through for this persona.");
    lines.push("");
  }

  if (e.overrankedLowRelevance.length > 0) {
    lines.push(
      `**Low-relevance items that still cracked the top 10** (${e.overrankedLowRelevance.length} of 10): ` +
        e.overrankedLowRelevance.map((r) => `${r.title} (${r.groundTruth.relevance}/3)`).join(", ") +
        "."
    );
    lines.push("");
  }

  if (e.missedRelevant.length > 0) {
    lines.push(
      "**Relevant, eligible opportunities that ranked outside the top 10:** " +
        e.missedRelevant.map((r) => `${r.title} (rank not shown, score ${r.score})`).join(", ") +
        "."
    );
    lines.push("");
  }

  lines.push(
    `**Metrics** — Precision@5: ${num(e.metrics.precisionAt5)} · Precision@10: ${num(e.metrics.precisionAt10)} · ` +
      `Recall@10: ${num(e.metrics.recallAt10)} · NDCG@10: ${num(e.metrics.ndcgAt10, 3)} · ` +
      `Eligibility accuracy: ${pct(e.eligibilityAccuracyResult.accuracy)} ` +
      `(${e.eligibilityAccuracyResult.comparisons.length - e.eligibilityAccuracyResult.mismatches.length}/${e.eligibilityAccuracyResult.comparisons.length} confident cases correct, ` +
      `${e.eligibilityAccuracyResult.excludedCount} cases excluded as ambiguous/structural-gap).`
  );
  lines.push("");

  if (e.truncatedExplanationEntries.length > 0) {
    lines.push(
      `**Explanation completeness**: ${e.truncatedExplanationEntries.length} of this persona's top-10 results had ` +
        `at least one real, computed matching signal that was *not* shown, due to the fixed 4-reason display cap: ` +
        e.truncatedExplanationEntries.map((r) => r.title).join(", ") +
        "."
    );
    lines.push("");
  }

  return lines.join("\n");
}

function main() {
  const results = runFullEvaluation();
  const A = results.A,
    B = results.B,
    C = results.C,
    D = results.D;

  const totalExplanationChecks = PERSONAS.reduce((sum, p) => sum + results[p.id].explanationChecks.length, 0);
  const totalUnverified = PERSONAS.reduce(
    (sum, p) => sum + results[p.id].explanationChecks.filter((c) => c.recognized && !c.verified).length,
    0
  );
  const totalUnrecognized = PERSONAS.reduce(
    (sum, p) => sum + results[p.id].explanationChecks.filter((c) => !c.recognized).length,
    0
  );
  const goalReasonShown = PERSONAS.some((p) =>
    results[p.id].topResults.some((r) => r.reasons.includes("This aligns with the goals you described"))
  );

  const report = `# Polaris — Recommendation Engine Baseline

Generated by \`scripts/generate-recommendation-baseline.ts\`, which runs the **unmodified**
current recommendation engine (\`lib/matching/scoring.ts\` / \`eligibility.ts\`, called exactly
as \`generateFeed\` calls them) against the evaluation framework in \`tests/evaluation/\`: four
synthetic personas and a hand-built, deliberately difficult 24-opportunity catalog with known
ground truth. No production recommendation logic was changed to produce this report — this is
a baseline, not a result of tuning.

See \`docs/backend-roadmap.md\` Part 12 for the evaluation framework's design rationale, and
\`docs/recommendation-roadmap.md\` for the engine's documented current weights and known issues
prior to this run.

## Methodology, in brief

- **Personas**: four hand-built profiles spanning different stages, citizenships, experience
  levels, and goals (full detail in \`tests/evaluation/personas.ts\`).
- **Catalog**: 24 opportunities (\`tests/evaluation/catalog.ts\`), each hand-labeled per persona
  with an expected eligibility (\`true\`/\`false\`/\`"ambiguous"\`/\`"structural-gap"\`) and a 0-3
  relevance grade, independent of what the code computes — the ground truth was written before
  reading this report's results, not fitted to them.
- **"Ambiguous"** ground truth is used only for one opportunity whose requirement text
  ("several years of relevant experience") doesn't resolve to a clean yes/no even for a human
  reader. **"Structural-gap"** is used only for two gender-restricted opportunities — the
  \`Profile\` model has no gender field at all, so there is no persona attribute to evaluate
  eligibility against; this is a data-model gap, not a scoring judgment call, and both are
  **excluded from the eligibility-accuracy and ranking-quality metrics** rather than guessed.
- **Precision@K / Recall@K**: standard definitions against each persona's hand-labeled
  "relevant" set (grade ≥2 **and** hand-labeled eligible — an opportunity we believe is truly
  ineligible never counts as a good recommendation, however relevant it looks).
- **NDCG@10**: linear-gain (not exponential-gain) DCG with a log2(rank+1) position discount,
  stated explicitly because both are legitimate conventions and the choice changes the number.
  An item whose eligibility ground truth isn't confidently \`true\` contributes 0 relevance to
  this metric, even in the actual ranking — so a highly-scored but ambiguously-eligible item
  sitting at rank 1 *lowers* NDCG rather than inflating it. See Persona D below for a concrete
  case.
- **Eligibility accuracy**: fraction of confident (non-ambiguous, non-structural-gap)
  persona/opportunity pairs where the engine's actual \`eligible\` boolean matches the hand
  label.
- **Explanation accuracy**: every reason string shown in a persona's top 10 is pattern-matched
  against the exact templates \`scoring.ts\` generates, then mechanically checked against the
  persona/opportunity data it claims to be backed by.
- **What's deliberately NOT calculated**: Precision@K/Recall@K/NDCG against *real* user
  behavior, save rate, click-through rate, application rate, dismissal rate — none of these
  are meaningful yet because there is no real user interaction data. Reporting a number for
  them would be manufacturing false precision; see the Metrics section at the end instead.

---

## Aggregate summary

| Persona | Eligible/Total | P@5 | P@10 | R@10 | NDCG@10 | Eligibility accuracy |
|---|---|---|---|---|---|---|
| A — Aisha (SWE → AI/ML) | ${A.eligibleCount}/${A.totalCatalogSize} | ${num(A.metrics.precisionAt5)} | ${num(A.metrics.precisionAt10)} | ${num(A.metrics.recallAt10)} | ${num(A.metrics.ndcgAt10, 3)} | ${pct(A.eligibilityAccuracyResult.accuracy)} |
| B — Ben (Econ → Finance) | ${B.eligibleCount}/${B.totalCatalogSize} | ${num(B.metrics.precisionAt5)} | ${num(B.metrics.precisionAt10)} | ${num(B.metrics.recallAt10)} | ${num(B.metrics.ndcgAt10, 3)} | ${pct(B.eligibilityAccuracyResult.accuracy)} |
| C — Chidi (Policy → AI governance) | ${C.eligibleCount}/${C.totalCatalogSize} | ${num(C.metrics.precisionAt5)} | ${num(C.metrics.precisionAt10)} | ${num(C.metrics.recallAt10)} | ${num(C.metrics.ndcgAt10, 3)} | ${pct(C.eligibilityAccuracyResult.accuracy)} |
| D — Diana (PM → Entrepreneurship) | ${D.eligibleCount}/${D.totalCatalogSize} | ${num(D.metrics.precisionAt5)} | ${num(D.metrics.precisionAt10)} | ${num(D.metrics.recallAt10)} | ${num(D.metrics.ndcgAt10, 3)} | ${pct(D.eligibilityAccuracyResult.accuracy)} |

**Reading Precision@10 correctly**: each persona's "true relevant set" is only 2-3 opportunities
out of 24 (a realistic ratio — most of any real catalog is irrelevant to any one person), so
Precision@10 is mathematically capped at relevantSetSize/10 (0.20-0.30 here) even for a
*perfect* engine. The metric that actually says whether ranking is working is Recall@10 (did
the few genuinely relevant items get found at all) combined with NDCG@10 (were they found
*near the top*, not just somewhere in the top 10) — both reported above alongside precision so
neither number is read in isolation.

---

## Per-persona results

${personaSection(A)}

---

${personaSection(B)}

---

${personaSection(C)}

---

${personaSection(D)}

---

## Do the top recommendations actually make sense?

**Yes, for the topically-clean cases.** Every persona's #1 and #2 ranked result is a genuine,
correctly-reasoned match: Aisha gets the AI/ML software engineering internship and hackathon;
Ben gets the economics scholarship and investment banking internship; Chidi gets the AI/
technology governance conference and fellowship; Diana gets the startup advisory board and AI
product leadership fellowship. The shown "why" reasons for these are accurate and specific, not
generic filler. The core interest/skill/preference matching machinery works.

**The ranking quality degrades in a specific, identifiable way**: eligible-but-low-relevance
opportunities routinely fill out the rest of each persona's top 10. Every persona has multiple
rank-6-through-10 entries at relevance 0-1/3 (see "Low-relevance items that still cracked the
top 10" per persona above) — sitting alongside or above genuinely relevant items ranked lower.
The reason is visible in the score gaps: Aisha's #1 result scores 63, but ranks 4 through 10 are
tightly clustered at 29-38 regardless of whether they're topically relevant (AI/ML Product
Leadership, relevance 1) or not (Investment Banking Internship, relevance 0) — once interest
overlap is absent, every eligible opportunity converges toward the same "baseline" score built
from \`eligibilitySoftScore\`'s ~9-point no-stated-constraint default, \`preferenceScore\`'s
~4-6 points for free/remote, and \`timingScore\`'s ~6-10 points for having *any* open deadline —
none of which require actual relevance to the person. This isn't a bug in any single line of
code; it's the effect of roughly half the scoring weight (35 of 100 points: eligibility-soft 15
+ preference 15 + timing 10, minus overlap) being earnable by *any* eligible opportunity with no
topical connection at all.

**One ranking anomaly worth naming directly**: Persona D's top-ranked result ("Global Startup
Advisory Board Program," score 48) is the one opportunity in the catalog whose eligibility we
graded "ambiguous" (its experience requirement — "several years of relevant experience" — isn't
machine-parseable, so the hard gate never generates a violation for it, regardless of who's
asking). It happens to be genuinely on-topic for Diana, so this may well be a correct
recommendation — but the engine has no way to signal *any* uncertainty about it versus the
opportunities right below it whose eligibility is unambiguous. It's presented with the same
confidence as everything else.

---

## Cross-persona findings and systematic patterns

1. **The hard eligibility gate has real, evidence-backed correctness bugs, some of them
   universal across personas.** This run found four distinct, independently-triggered bugs:
   - **Freshness**: a deadline 60 days in the past does not exclude an opportunity whose
     \`status\` field was never updated — confirmed to wrongly admit "AI Bootcamp — Summer 2026"
     for **all four personas**, not an isolated case.
   - **Range misparsing**: "Early Career AI Ethics Fellowship" states "0-3 years professional
     experience," intending to *restrict* to early-career applicants. The experience-parsing
     regex (\`/(\\d+)\\s*\\+?\\s*years?/i\`) matches the *first number immediately followed by
     "years"* — in "0-3 years," that's "3," not "0" — so the requirement is silently inverted
     into "requires 3+ years." This **wrongly excludes** the three personas who genuinely fit
     the intended early-career band (Aisha: 1yr, Ben: 0yr, Chidi: 2yr) and **wrongly admits**
     the one persona the listing explicitly meant to exclude (Diana: 10yr). Confirmed for all
     four personas, in both directions — the single most damaging bug found in this run, because
     it doesn't just fail to gate, it actively gates backwards.
   - **Domain-blind experience matching**: "AI Governance Fellowship" requires "3+ years
     *policy* experience." Diana's 10 years of *product management* experience numerically
     clears "3+" and is accepted, because the regex extracts a number with no concept of what
     domain that experience needs to be in.
   - **Stage-matching by substring, not by word/keyword**: "Undergraduate Economics
     Scholarship" requires \`educationRequirements: ["undergraduate"]\`. Persona C (a GRADUATE
     student) is incorrectly marked eligible, because the stage-check does
     \`requirementText.includes(keyword)\`, and the literal string \`"undergraduate"\` contains
     the substring \`"graduate"\` — one of the keywords associated with the \`GRADUATE\` stage.
   Together, eligibility accuracy across the four personas ranges from
   ${pct(Math.min(A.eligibilityAccuracyResult.accuracy, B.eligibilityAccuracyResult.accuracy, C.eligibilityAccuracyResult.accuracy, D.eligibilityAccuracyResult.accuracy))}
   to ${pct(Math.max(A.eligibilityAccuracyResult.accuracy, B.eligibilityAccuracyResult.accuracy, C.eligibilityAccuracyResult.accuracy, D.eligibilityAccuracyResult.accuracy))}
   on confident, non-ambiguous ground truth — meaning roughly 1 in 10 hard-gate decisions in
   this catalog was wrong, in a system whose entire justification for a hard gate (rather than
   a soft ranking signal) is that it's supposed to be trustworthy specifically because it's
   deterministic.
2. **The gender-restriction gap is structural, not a scoring bug**: two catalog opportunities
   (a fellowship and a mentorship circle) explicitly state a gender requirement. Neither could
   be evaluated for correctness, because \`Profile\` has no gender field and \`MatchOpportunity\`
   (the shape the scoring engine actually receives) has no \`genderRequirement\` field either —
   the information is discarded before it ever reaches the eligibility gate. Confirmed by
   direct inspection, not inference: every persona shows both opportunities as simply
   "eligible," with no signal that a gender requirement was ever present.
3. **Explanation correctness is high; explanation completeness is not.**
   ${totalUnverified} of ${totalExplanationChecks} recognized reason strings shown across all
   four personas' top 10s failed verification against the underlying data (i.e., essentially
   none — the "why" text is mechanically trustworthy, matching the architecture's intent that
   nothing is freely generated). ${totalUnrecognized > 0 ? `${totalUnrecognized} reason string(s) did not match any known template and should be reviewed.` : "Every shown reason matched a known, verifiable template."}
   However, ${PERSONAS.filter((p) => results[p.id].truncatedExplanationEntries.length > 0).length}
   of 4 personas had at least one top-10 result where a real, computed signal was silently
   dropped by the fixed 4-reason cap — for example, Aisha's #1 result (AI/ML Software
   Engineering Internship) actually earned a "Matches your interest in internship
   opportunities" signal (INTERNSHIP is explicitly one of her preferred types) that never
   appears in the shown reasons, because interest (2 reasons) + skills (1) + preference (2,
   remote + type match) = 5 available reasons compete for a 4-slot cap and the cap is
   positional, not importance-ranked.
   ${goalReasonShown ? "" : `**Notably, the goal-alignment reason ("This aligns with the goals you described") never appeared once across all 40 top-10 slots in this run**, despite every persona having a well-formed aspiration statement and the catalog containing opportunities squarely on-topic for each. This is consistent with the local hashed-embedding's known synonym-blindness (docs/recommendation-roadmap.md) — it needs literal word overlap between aspiration text and opportunity text to cross its own display threshold, and evidently doesn't get there even in these designed-to-match cases.`}
4. **Ranking has a real, structural relevance ceiling, not an isolated tuning problem.** As
   detailed above, roughly a third of total possible score (eligibility-soft + preference +
   timing) is earnable by *any* eligible opportunity regardless of topical connection to the
   person, which is why low-relevance items routinely fill half of every persona's top 10.

---

## Punch list, ranked by severity

1. **Range-requirement misparsing actively inverts eligibility** (found via "Early Career AI
   Ethics Fellowship," affects all 4 personas, 2 in the wrong direction each). Highest
   severity: this doesn't just fail to protect a hard gate, it produces confidently wrong
   answers in both directions on a single, realistic requirement phrasing.
2. **A passed deadline never excludes an opportunity** unless a human/source also flipped
   \`status\` to \`CLOSED\` — confirmed to affect every persona identically. High severity and
   high real-world likelihood (source data going stale is normal, not an edge case).
3. **Gender-restricted opportunities cannot be gated at all** — a full category of hard
   eligibility requirement is invisible to the matching layer, not merely unenforced by a
   fixable rule. Requires a schema change (add gender to \`Profile\`, thread it through
   \`MatchOpportunity\` and \`checkEligibility\`), not just a logic fix.
4. **Stage-matching uses substring containment instead of exact/word-boundary matching**,
   producing at least one confirmed false-eligible ("undergraduate" ⊃ "graduate"). Likely to
   have sibling cases beyond the one this catalog happened to construct.
5. **Experience-requirement matching has no concept of domain** (policy vs. product vs.
   engineering years are all just "years"), producing a confirmed false-eligible on the
   brief's own worked-example opportunity, for a different persona than the example targets.
6. **The reason-selection cap silently drops real, positive signals** rather than the
   *weakest* ones — a presentation-layer bug, lower severity than the eligibility issues above
   since it doesn't affect who gets recommended, only how well the "why" is explained.
7. **Roughly a third of the scoring range is earnable with zero topical relevance**,
   producing a persistent floor of low-relevance items in every persona's top 10 — a tuning/
   weighting issue, not a correctness bug, but the most consistently-observed pattern in this
   run and the most directly responsible for "does the top 10 actually make sense" being a
   qualified yes rather than an unqualified one.

Items 1-5 are eligibility/hard-gate correctness bugs — per \`docs/backend-roadmap.md\` Part 15,
these are exactly what P0 priority #2 ("eligibility engine hardening") should target first,
now backed by concrete, reproducible cases instead of a general suspicion. Item 6 belongs to
P0 priority #3 ("ranking correctness fixes"). Item 7 is the clearest evidence yet that P0
priority #3's weight/signal work is worth doing, not merely a documentation nicety.

---

## Metrics that could not be meaningfully calculated

Per the request not to manufacture numbers where they wouldn't be meaningful:

- **Precision@K / Recall@K / NDCG@K against real user judgments** — not calculated. The
  numbers reported above are against *hand-authored* ground truth for a *synthetic* catalog,
  which measures "does the engine behave the way we intend it to" — a legitimate and useful
  thing to measure, but not the same claim as "does the engine satisfy real users," which
  requires real interaction data that doesn't exist yet.
- **Save rate, click-through rate, application rate, dismissal rate, "not relevant" rate** —
  not calculated; no behavioral event tracking exists in the product yet (confirmed absent in
  \`docs/backend-roadmap.md\` Part 1). These become measurable the moment that tracking exists.
- **Statistical confidence intervals on any of the above** — not applicable to a 4-persona,
  24-item deterministic evaluation; these numbers describe this specific catalog precisely,
  not a sampled estimate of a larger population.

---

*Generated ${new Date().toISOString().slice(0, 10)}. Regeneratable via \`npm run eval:baseline\`;
the tables above are computed live from \`tests/evaluation/\` each run, so if production
scoring logic changes, re-running this script will reflect that — the narrative prose in this
version describes the specific run captured on the date above and should be re-reviewed (not
blindly trusted) after any scoring change.*
`;

  const outPath = path.resolve(__dirname, "../docs/recommendation-baseline.md");
  writeFileSync(outPath, report, "utf-8");
  console.log(`Wrote ${outPath}`);
  console.log(`Catalog size: ${CATALOG.length}. Personas: ${PERSONAS.length}.`);
}

main();
